name: "local-validate"
description: "Validate workflow locally"
inputs:
  reana_specs:
    description: "REANA specification path to validate"
    required: true
  validator_image:
    description:
      "REANA-Workflow-Validator image used to load the specifications"
    required: false
    default: "docker.io/reanahub/reana-workflow-validator:0.95.0-alpha.1"
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Validate workflow
      run: '"${{ github.action_path }}/validate.sh" ${{ inputs.reana_specs }}'
      env:
        VALIDATOR_IMAGE: ${{ inputs.validator_image }}
      shell: bash
